services:
  # Backend service
  - type: web
    name: the-raven-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://ssd1:#Soubhagya8763@cluster0.hzba1vr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key_here
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  # Frontend service
  - type: web
    name: the-raven-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://the-raven-backend.onrender.com
      - key: PORT
        value: 3000 